# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: d9400150-capi-aws
  namespace: d9400150
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: d9400150-capi-aws
subjects:
- kind: ServiceAccount
  name: d9400150-capi-aws
